### ISSUE TITLE
Switch to Travis Pro?

### ISSUE THREAD

**Issue by splattael** [ElixirRuhr/elixir.ruhr#16]
It seems that https://travis-ci.org/ElixirRuhr/elixir.ruhr/ stopped working somehow.

It does not work for new pull requests neither (see #15).

Should we switch to Travis Pro (which is free for Open Source)?

Any other alternatives we should consider?

**Comment by jnbt** [comment]
I've reactivated the Travis instance. Seems that the project was deactivated because of inactivity.

**Comment by jnbt** [comment]
I wasn't able to manually migrate to Pro as this seems currently not available:

From: https://docs.travis-ci.com/user/open-source-on-travis-ci-com/#Existing-Open-Source-Repositories-on-travis-ci.org

> Open source projects and their build history will continue to run on travis-ci.org for now.
>
>However, open source repositories will be migrated to travis-ci.com gradually, beginning at the end of Q2 2018. You will receive an email when the migration for a repository is complete. This is an opt-in process: to have a repository migrated over, it must first be activated on travis-ci.com.
>
>Currently, open source repositories that were private in any time in their history may be added to travis-ci.com. The option to migrate to travis-ci.com for active open source repositories that were always open source will come soon.

**Comment by splattael** [comment]
@jnbt Thanks! [travis-ci.org](https://travis-ci.org/ElixirRuhr/elixir.ruhr/builds) works now :green_heart:
